config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users, only: [:show]
  resources :examinations, except: [:destroy]

  namespace :admin do
    resources :subjects
    resources :users, only: [:index, :update]
    resources :questions
    resources :examinations, only: [:index, :show, :update]
  end
  resources :questions
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :examinations, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50},
    uniqueness: {case_sensitive: false}
  validates :description, presence: true, length: {maximum: 150}
  validates :total_question, presence: true,
    numericality: {only_integer: true, greater_than: 0}
  validates :duration, presence: true,
    numericality: {only_integer: true, greater_than: 0}

  after_create :notify_user

  def notify_user
    UserNotification.new(self).send_notify_user
  end
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  before_action :check_admin
  load_and_authorize_resource
  before_action :check_delete_subject, only: :destroy
  def index
    @search = Subject.search params[:q]
    @subjects = @search.result.order(created_at: :desc)
      .page(params[:page]).per Settings.per_page
    @subject = Subject.new
  end

  def new
  end

  def create
    @subject.save
    respond_to do |format|
        format.js
    end
  end

  def show
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t "controllers.admin.subjects_controller.update_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "controllers.admin.subjects_controller.update_error"
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t "controllers.admin.subjects_controller.delete_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "controllers.admin.subjects_controller.delete_error"
      redirect_to :back
    end
  end

  private
  def subject_params
    params.require(:subject).permit :name, :total_question,
      :duration, :description
  end

  def check_delete_subject
    if @subject.examinations.any?
      flash[:danger] = t "controllers.admin.subjects_controller.cant_delete"
      redirect_to admin_subjects_path
    end
  end
end

app/views/admin/subjects/_form.html.erb
<%= form_for [:admin, @subject] do |f| %>
  <%= render "shared/error_messages", object: @subject %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :total_question %>
  <%= f.text_field :total_question, class: "form-control" %>

  <%= f.label :duration %>
  <%= f.text_field :duration, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.submit class: "btn btn-primary create_subject"  %>
<% end %>

app/views/admin/subjects/_subject.html.erb
<tr>
  <td></td>
  <td><%= subject.name %></td>
  <td><%= subject.total_question %></td>
  <td><%= subject.duration %> minutes</td>
  <td><%= subject.description %></td>
  <td>
    <%= link_to edit_admin_subject_path(subject),
      data: {toggle: "tooltip", placement: "top"}, title: t("edit") do %>
      <span class= "glyphicon glyphicon-edit"></span>
    <% end %> |
    <%= link_to admin_subject_path(subject),
      method: :delete, data: {toggle: "tooltip", placement: "top",
        confirm: t("views.admin.subjects.delete_confirm")},
        title: t("delete") do %>
      <span class="glyphicon glyphicon-trash text-danger"></span>
    <% end %>
  </td>
</tr>

app/views/admin/subjects/create.js.erb
<% if @subject.invalid? %>
  $('.subject-errors').append('<%= j render "shared/error_messages", object: @subject %>');
  $('.subject-errors').delay(5000).slideUp();
<% else %>
  $('#subjects-index').append('<%= j (render @subject) %>');
  $('#new-subject').modal('hide');
  $('#subject_name').val('');
  $('#subject_total_question').val('');
  $('#subject_duration').val('');
  $('#subject_description').val('');
  $('#admin_subject tbody tr:last').find('td:first').text($('#admin_subject tbody tr').length);
<% end %>

app/views/admin/subjects/edit.html.erb
<%= provide :title, t("views.admin.subjects.edit")  %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= t "views.admin.subjects.edit" %></h1>
      <%= render "form" %>
  </div>
</div>

app/views/admin/subjects/index.html.erb
 <% provide :title, t("views.admin.subjects.all_subject") %>
<div class="row">
  <h1><%= t "views.admin.subjects.all_subject" %></h1>

  <div class="subject-search">
    <%= search_form_for [:admin, @search], class: "form-inline" do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name_cont, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :duration %>
        <%= f.text_field :duration_eq, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :total_question %>
        <%= f.text_field :total_question_eq, class: "form-control" %>
      </div>
      <%= button_tag(type: "submit", class: "btn btn-primary",
        name: "commit", value: "conceal") do %>
        <span class="glyphicon glyphicon-search"></span>
      <% end %>
    <% end %>
  </div>

  <button class="btn btn-primary btn-lg" data-toggle="modal"
    data-target="#new-subject" data-whatever="@fat">
      <span class="glyphicon glyphicon-plus add_subject">
        <%= t("views.admin.subjects.add_new")%>
      </span>
  </button>

  <table class="table table-striped table-hover table-bordered" id="admin_subject">
    <thead>
      <tr class="info">
        <th><%= t "views.admin.subjects.index" %></th>
        <th><%= t "views.admin.subjects.name" %></th>
        <th><%= t "views.admin.subjects.total_question" %></th>
        <th><%= t "views.admin.subjects.duration" %></th>
        <th><%= t "views.admin.subjects.description" %></th>
        <th class="actions"><%= t "views.admin.subjects.actions" %></th>
      </tr>
    </thead>
    <tbody id="subjects-index">
      <% @subjects.each_with_index do |subject, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= subject.name %></td>
          <td><%= subject.total_question %></td>
          <td><%= subject.duration %> minutes</td>
          <td><%= subject.description %></td>
          <td>
            <%= link_to edit_admin_subject_path(subject),
              data: {toggle: "tooltip", placement: "top"}, title: t("edit") do %>
              <span class= "glyphicon glyphicon-edit"></span>
            <% end %> |
            <%= link_to admin_subject_path(subject),
              method: :delete, data: {toggle: "tooltip", placement: "top",
                confirm: t("views.admin.subjects.delete_confirm")},
                title: t("delete") do %>
              <span class="glyphicon glyphicon-trash text-danger"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @subjects %>
</div>

<!-- Modal -->
<div class="modal fade" id="new-subject" tabindex="-1" role="dialog"
  aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Create new subject</h4>
      </div>
      <%= form_for [:admin, @subject], remote: true do |f| %>
        <div class="modal-body">
          <div class="subject-errors">
          </div>

          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.label :total_question %>
          <%= f.text_field :total_question, class: "form-control" %>

          <%= f.label :duration %>
          <%= f.text_field :duration, class: "form-control" %>

          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control" %>

          <%= f.submit class: "btn btn-primary create_subject"  %>
        </div>
      <% end %>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/subjects/new.html.erb
<% provide :title, t("controllers.admin.subjects_controller.title") %>
<% provide :button_text, t("controllers.admin.subjects_controller.new_button") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <center>
      <h2><%= t "controllers.admin.subjects_controller.new_title" %></h2>
    </center>
      <%= render "form" %>
  </div>
</div>