config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users, only: [:show]
  resources :examinations, except: [:destroy]

  namespace :admin do
    resources :subjects
    resources :users, only: [:index, :update]
    resources :questions
    resources :examinations, only: [:index, :show, :update]
  end
  resources :questions
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p><%= t "views.layouts.footer.content" %></p>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">
    <nav>
      <%= link_to root_path  do %>
        <%= image_tag('logo.png', size: "140x50")%>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= "active" if current_page?(root_path) %>">
          <%= link_to t("views.layouts.header.home"), root_url %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.admin? || current_user.supper? %>
            <li class="<%= "active" if current_page?(admin_subjects_path) %>">
              <%= link_to t("views.admin.subjects.all_subject"),
                admin_subjects_path %>
            </li>
            <li class="<%= "active" if current_page?(admin_questions_path) %>">
              <%= link_to t("views.admin.question.questions"),
                admin_questions_path %>
            </li>
            <li class="<%= "active" if current_page?(admin_examinations_path) %>">
              <%= link_to t("views.admin.exams.user_exams"),
              admin_examinations_path %></li>
            <li class="<%= "active" if current_page?(admin_users_path) %>">
              <%= link_to t("views.admin.users.title"),
                admin_users_path %>
            </li>
            <li class="<%= "active" if current_page?(destroy_user_session_path) %>">
              <%= link_to t("views.layouts.header.signout"),
              destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="<%= "active" if current_page?(examinations_path) %>">
              <%= link_to t("views.layouts.header.exams"), examinations_path %>
            </li>
            <li class="<%= "active" if current_page?(questions_path) %>">
              <%= link_to t("views.layouts.header.contribute_questions"), questions_path %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("views.layouts.header.profile"), user_path(current_user) %></li>
                <li><%= link_to t("views.layouts.header.edit"), edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <li><%= link_to t("views.layouts.header.signout"),
                    destroy_user_session_path, method: :delete %>
                  </li>
                </li>
              </ul>
            </li>
          <% end %>
        <% else %>
          <li class="<%= "active" if current_page?(new_user_registration_path) %>">
            <%= link_to t("views.layouts.header.signup"),
            new_user_registration_path %>
          </li>
          <li class="<%= "active" if current_page?(new_user_session_path) %>">
            <%= link_to t("views.layouts.header.signin"),
            new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track": true %>
  <%= javascript_include_tag "application", "data-turbolinks-track": true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>